import {Metadata} from 'next'
import { ErrorWrapper } from './error-wrapper'

export const metadata: Metadata = {
  title: {
    default: 'Default root layout title', //acts as a fallback for any child routes that don't specify their own title
    template: '%s | Template title root layout', //useful when you want to add consistent prefixes or suffixes to the title, this property applies to child rooutes
    //the page title will replace the %s in the template, this pattern is useful in multipage applications
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body>
      <header
        style={{
          backgroundColor: "lightblue",
          padding: "1rem",
        }}
      >
        <p>Header</p>
      </header>
      <ErrorWrapper>
      {children}
      </ErrorWrapper>
      <footer
        style={{
          backgroundColor: "ghostwhite",
          padding: "1rem",
        }}
      >
        <p>Footer</p>
      </footer>
    </body>
  </html>
  )
}
